package domain

type Config struct {
	// Global Settings
	ASDPVersion    string   `yaml:"asdp_version"`
	IgnorePatterns []string `yaml:"ignore_patterns"`

	// Scaffolding Policy
	Scaffold ScaffoldConfig `yaml:"scaffold"`

	// Sync Policy
	Sync SyncConfig `yaml:"sync"`

	// Validation Policy
	Validation ValidationConfig `yaml:"validation"`

	// New: Parsing & Hashing Policy
	Parsing ParsingConfig `yaml:"parsing"`
	Hasher  HasherConfig  `yaml:"hasher"`

	// New: UI & Templates
	UI UIConfig `yaml:"ui"`

	// New: MCP Metadata
	MCP MCPConfig `yaml:"mcp"`

	// New: System Paths
	System SystemConfig `yaml:"system"`
}

type SystemConfig struct {
	GlobalAssetsDir string `yaml:"global_assets_dir"` // ~/.asdp/core/agent
	DefaultAgentDir string `yaml:"default_agent_dir"` // .agent
}

type ParsingConfig struct {
	Go          GoParsingConfig    `yaml:"go"`
	Ctags       CtagsParsingConfig `yaml:"ctags"`
	SkipHidden  bool               `yaml:"skip_hidden"`
	IgnoreFiles []string           `yaml:"ignore_files"`
}

type GoParsingConfig struct {
	SkipTests bool `yaml:"skip_tests"`
}

type CtagsParsingConfig struct {
	Binary       string   `yaml:"binary"`
	Recurse      bool     `yaml:"recurse"`
	Fields       string   `yaml:"fields"`
	Excludes     []string `yaml:"excludes"`
	AllowMissing bool     `yaml:"allow_missing"`
}

type HasherConfig struct {
	Algorithm     string   `yaml:"algorithm"`
	IgnoredDirs   []string `yaml:"ignored_dirs"`
	IgnoredFiles  []string `yaml:"ignored_files"`
	Recursive     bool     `yaml:"recursive"`
	ExcludeHidden bool     `yaml:"exclude_hidden"`
}

type UIConfig struct {
	BannerText          string `yaml:"banner_text"`
	FallbackDescription string `yaml:"fallback_description"`
	AutoGeneratedModel  string `yaml:"auto_generated_model"`
	AutoGeneratedTree   string `yaml:"auto_generated_tree"`
}

type MCPConfig struct {
	ProtocolVersion string                  `yaml:"protocol_version"`
	ToolDefinitions map[string]ToolMetadata `yaml:"tool_definitions"`
}

type ToolMetadata struct {
	Description string                 `yaml:"description"`
	InputSchema map[string]interface{} `yaml:"input_schema"`
}

type ScaffoldConfig struct {
	DefaultType     string `yaml:"default_type"`     // "library"
	SpecTemplate    string `yaml:"spec_template"`    // The raw string for codespec.md
	ModelTemplate   string `yaml:"model_template"`   // The raw string for codemodel.md
	RequiredContext bool   `yaml:"required_context"` // Enforce non-empty context (true)
}

type SyncConfig struct {
	Tree  TreeSyncConfig  `yaml:"tree"`
	Model ModelSyncConfig `yaml:"model"`
}

type TreeSyncConfig struct {
	ShallowDirs      []string `yaml:"shallow_dirs"`      // node_modules, vendor
	IgnoredDirs      []string `yaml:"ignored_dirs"`      // .git, .idea, etc
	DefaultComponent string   `yaml:"default_component"` // "module"
	DependencyType   string   `yaml:"dependency_type"`   // "dependency"
	HeaderTemplate   string   `yaml:"header_template"`   // "Project Hierarchy..."
	FallbackDesc     string   `yaml:"fallback_desc"`     // "(No specification found)"
}

type ModelSyncConfig struct {
	IntegrityAlgo  string `yaml:"integrity_algo"`  // "sha256"
	FirstSyncHash  string `yaml:"first_sync_hash"` // "PENDING_FIRST_SYNC"
	HeaderTemplate string `yaml:"header_template"` // "Semantic Model..."
}

type ValidationConfig struct {
	MandatoryFiles   []string        `yaml:"mandatory_files"`   // ["codetree.md"]
	ModuleFiles      []string        `yaml:"module_files"`      // ["codespec.md", "codemodel.md"]
	ForbiddenStrings []string        `yaml:"forbidden_strings"` // ["TODO"]
	RequiredSpecKeys []string        `yaml:"required_spec_keys"`
	Freshness        FreshnessConfig `yaml:"freshness"`
}

type FreshnessConfig struct {
	WatchedExtensions []string `yaml:"watched_extensions"` // [.go, .ts, .js, .py]
	IgnoredExtensions []string `yaml:"ignored_extensions"` // [.md, _test.go]
}

// DefaultConfig returns the "hardcoded" configuration that mirrors the original codebase behavior.
// This is the source of truth if no config file is provided.
func DefaultConfig() *Config {
	ignoreList := []string{
		"node_modules", "vendor", "packages", "bower_components",
		"venv", ".venv", "anaconda", "conda", "env", ".env",
		"bin", "obj", "dist", "target", "build", "out",
		".vscode", ".idea", ".git", ".hg", ".svn", ".cache",
		"__pycache__", "structs",
	}

	return &Config{
		ASDPVersion:    Version,
		IgnorePatterns: ignoreList,
		Parsing: ParsingConfig{
			SkipHidden:  true,
			IgnoreFiles: []string{"*_test.go", ".DS_Store"},
			Go: GoParsingConfig{
				SkipTests: true,
			},
			Ctags: CtagsParsingConfig{
				Binary:       "ctags",
				Recurse:      false,
				Fields:       "+nKe",
				Excludes:     []string{"*.go"},
				AllowMissing: true,
			},
		},
		Hasher: HasherConfig{
			Algorithm:     "sha256",
			Recursive:     true,
			ExcludeHidden: true,
			IgnoredDirs:   ignoreList,
			IgnoredFiles:  []string{"*.md", "*_test.go", ".DS_Store"},
		},
		UI: UIConfig{
			BannerText:          "ASDP Protocol Kit",
			FallbackDescription: "(No specification found)",
			AutoGeneratedModel:  "\n# Semantic Model\n\nAuto-generated by ASDP Sync.\n",
			AutoGeneratedTree:   "\n# Project Hierarchy\n\nAuto-generated by ASDP SyncTree.\n",
		},
		MCP: MCPConfig{
			ProtocolVersion: "2024-11-05",
			ToolDefinitions: map[string]ToolMetadata{
				"asdp_query_context": {
					Description: "Retrieve the ASDP context (Spec, Model, Freshness) for a given absolute path. Result: Returns a JSON object containing the merged CodeSpec (intent), CodeModel (structure), and current freshness status, allowing an agent to quickly understand a module's contract and implementation.",
					InputSchema: map[string]interface{}{
						"type": "object",
						"properties": map[string]interface{}{
							"path": map[string]interface{}{
								"type":        "string",
								"description": "ABSOLUTE path to the module (e.g. /home/user/project/module)",
							},
						},
						"required": []string{"path"},
					},
				},
				"asdp_sync_codemodel": {
					Description: "Automatically scans the source code and updates the codemodel.md file. Result: Returns a SyncResult JSON with the count of symbols identified (functions, structs, interfaces including start/end lines) and the integrity hash of the source files.",
					InputSchema: map[string]interface{}{
						"type": "object",
						"properties": map[string]interface{}{
							"path": map[string]interface{}{
								"type":        "string",
								"description": "ABSOLUTE path to the module (e.g. /home/user/project/module)",
							},
						},
						"required": []string{"path"},
					},
				},
				"asdp_sync_codetree": {
					Description: "Automatically scans the project directory and updates the codetree.md file. Result: Returns a JSON representation of the project hierarchy, listing all modules and their ASDP compliance status (presence of codespec/codemodel).",
					InputSchema: map[string]interface{}{
						"type": "object",
						"properties": map[string]interface{}{
							"path": map[string]interface{}{
								"type":        "string",
								"description": "ABSOLUTE path to the project root or sub-directory.",
							},
						},
						"required": []string{"path"},
					},
				},
				"asdp_scaffold": {
					Description: "Create a new ASDP-compliant module or backfill missing files (codespec/codemodel) in an existing one. Safe to run on existing directories; will not overwrite existing files. Result: Returns a success message.",
					InputSchema: map[string]interface{}{
						"type": "object",
						"properties": map[string]interface{}{
							"name": map[string]interface{}{
								"type":        "string",
								"description": "Module name. Use '.' to scaffold directly in the provided path.",
							},
							"type": map[string]interface{}{
								"type":        "string",
								"description": "Module type (library, service, app). Default: library",
							},
							"path": map[string]interface{}{
								"type":        "string",
								"description": "ABSOLUTE parent directory (or target directory if name='.').",
							},
							"title": map[string]interface{}{
								"type":        "string",
								"description": "Title of the module (e.g. 'User Authentication Service'). Required.",
							},
							"summary": map[string]interface{}{
								"type":        "string",
								"description": "Brief summary of the module's purpose. Required.",
							},
							"context": map[string]interface{}{
								"type":        "string",
								"description": "Detailed context and reasoning for this module. Required.",
							},
						},
						"required": []string{"name", "path", "title", "summary", "context"},
					},
				},
				"asdp_init_agent": {
					Description: "Copies ASDP Agent assets into the local project. Result: Returns a list of files copied into the .agent/ directory (Rules, Workflows, etc.) to enable ASDP-native agent behavior.",
					InputSchema: map[string]interface{}{
						"type": "object",
						"properties": map[string]interface{}{
							"path": map[string]interface{}{
								"type":        "string",
								"description": "ABSOLUTE project root path (e.g. /home/user/project)",
							},
						},
					},
				},
				"asdp_init_project": {
					Description: "Unified initialization of an ASDP project. Result: Sets up .agent/ at project path AND anchors the CodeTree at a specified code path, ensuring the AI starts from the real code.",
					InputSchema: map[string]interface{}{
						"type": "object",
						"properties": map[string]interface{}{
							"path": map[string]interface{}{
								"type":        "string",
								"description": "ABSOLUTE project repository root path.",
							},
							"code_path": map[string]interface{}{
								"type":        "string",
								"description": "ABSOLUTE path to where the actual code starts (e.g. /repo/tools).",
							},
						},
						"required": []string{"path", "code_path"},
					},
				},
				"asdp_validate": {
					Description: "Audit the ASDP project state. Returns a report of Errors (invalid state, integration blocking) and Warnings (staleness). Checks for mandatory files, strict content compliance, and synchronization freshness.",
					InputSchema: map[string]interface{}{
						"type": "object",
						"properties": map[string]interface{}{
							"path": map[string]interface{}{
								"type":        "string",
								"description": "ABSOLUTE path to the project root.",
							},
						},
						"required": []string{"path"},
					},
				},
				"asdp_function_info": {
					Description: "Retrieve detailed information about a function/symbol, including its source code, documentation, and the codespec/codemodel context of its module.",
					InputSchema: map[string]interface{}{
						"type": "object",
						"properties": map[string]interface{}{
							"path": map[string]interface{}{
								"type":        "string",
								"description": "ABSOLUTE path to the module containing the symbol.",
							},
							"symbol": map[string]interface{}{
								"type":        "string",
								"description": "Name of the symbol (function, struct, etc.) to inspect.",
							},
						},
						"required": []string{"path", "symbol"},
					},
				},
			},
		},
		Scaffold: ScaffoldConfig{
			DefaultType:     "library",
			RequiredContext: true,
			SpecTemplate: `---
asdp_version: "{{.ASDPVersion}}"
last_modified: {{.LastModified}}
id: "{{.ID}}"
type: "{{.Type}}"
title: "{{.Title}}"
summary: "{{.Summary}}"
capabilities: []
dependencies: []
requirements: []
exports: []
---
# {{.Title}} Specification

## Context
{{.Context}}

## Requirements
- ...
`,
			ModelTemplate: `---
asdp_version: "{{.ASDPVersion}}"
integrity:
  src_hash: "PENDING_FIRST_SYNC"
  algorithm: "sha256"
  checked_at: {{.CheckedAt}}
symbols: []
---
# Semantic Model

Auto-generated by ASDP. Run asdp_sync to populate.
`,
		},
		Sync: SyncConfig{
			Tree: TreeSyncConfig{
				ShallowDirs:      []string{"node_modules", "vendor", "bower_components"},
				IgnoredDirs:      ignoreList,
				DefaultComponent: "module",
				DependencyType:   "dependency",
				HeaderTemplate:   "\n# Project Hierarchy\n\nAuto-generated by ASDP SyncTree.\n",
				FallbackDesc:     "(No specification found)",
			},
			Model: ModelSyncConfig{
				IntegrityAlgo:  "sha256",
				FirstSyncHash:  "PENDING_FIRST_SYNC",
				HeaderTemplate: "\n# Semantic Model\n\nAuto-generated by ASDP Sync.\n",
			},
		},
		Validation: ValidationConfig{
			MandatoryFiles:   []string{"codetree.md"},
			ModuleFiles:      []string{"codespec.md", "codemodel.md"},
			ForbiddenStrings: []string{"TODO"},
			RequiredSpecKeys: []string{"title:", "summary:", "## Context"},
			Freshness: FreshnessConfig{
				WatchedExtensions: []string{".go", ".ts", ".js", ".py"},
				IgnoredExtensions: []string{".md", "_test.go"},
			},
		},
		System: SystemConfig{
			GlobalAssetsDir: ".asdp/core/agent",
			DefaultAgentDir: ".agent",
		},
	}
}
