package domain

type Config struct {
	// Global Settings
	ASDPVersion    string   `yaml:"asdp_version"`
	IgnorePatterns []string `yaml:"ignore_patterns"`

	// Scaffolding Policy
	Scaffold ScaffoldConfig `yaml:"scaffold"`

	// Sync Policy
	Sync SyncConfig `yaml:"sync"`

	// Validation Policy
	Validation ValidationConfig `yaml:"validation"`
}

type ScaffoldConfig struct {
	DefaultType     string `yaml:"default_type"`     // "library"
	SpecTemplate    string `yaml:"spec_template"`    // The raw string for codespec.md
	ModelTemplate   string `yaml:"model_template"`   // The raw string for codemodel.md
	RequiredContext bool   `yaml:"required_context"` // Enforce non-empty context (true)
}

type SyncConfig struct {
	Tree  TreeSyncConfig  `yaml:"tree"`
	Model ModelSyncConfig `yaml:"model"`
}

type TreeSyncConfig struct {
	ShallowDirs      []string `yaml:"shallow_dirs"`      // node_modules, vendor
	IgnoredDirs      []string `yaml:"ignored_dirs"`      // .git, .idea, etc (specific to tree walker if diff from global? No, usually subset or same)
	DefaultComponent string   `yaml:"default_component"` // "module"
	DependencyType   string   `yaml:"dependency_type"`   // "dependency"
	HeaderTemplate   string   `yaml:"header_template"`   // "Project Hierarchy..."
	FallbackDesc     string   `yaml:"fallback_desc"`     // "(No specification found)"
}

type ModelSyncConfig struct {
	IntegrityAlgo  string `yaml:"integrity_algo"`  // "sha256"
	FirstSyncHash  string `yaml:"first_sync_hash"` // "PENDING_FIRST_SYNC"
	HeaderTemplate string `yaml:"header_template"` // "Semantic Model..."
}

type ValidationConfig struct {
	MandatoryFiles   []string        `yaml:"mandatory_files"`   // ["codetree.md"]
	ModuleFiles      []string        `yaml:"module_files"`      // ["codespec.md", "codemodel.md"]
	ForbiddenStrings []string        `yaml:"forbidden_strings"` // ["TODO"]
	RequiredSpecKeys []string        `yaml:"required_spec_keys"`
	Freshness        FreshnessConfig `yaml:"freshness"`
}

type FreshnessConfig struct {
	WatchedExtensions []string `yaml:"watched_extensions"` // [.go, .ts, .js, .py]
	IgnoredExtensions []string `yaml:"ignored_extensions"` // [.md, _test.go]
}

// DefaultConfig returns the "hardcoded" configuration that mirrors the original codebase behavior.
// This is the source of truth if no config file is provided.
func DefaultConfig() *Config {
	return &Config{
		ASDPVersion: Version,
		IgnorePatterns: []string{
			"node_modules", "vendor", "packages", "bower_components",
			"venv", ".venv", "anaconda", "conda", "env", ".env",
			"bin", "obj", "dist", "target", "build", "out",
			".vscode", ".idea", ".git", ".hg", ".svn", ".cache",
			"__pycache__", "structs",
		},
		Scaffold: ScaffoldConfig{
			DefaultType:     "library",
			RequiredContext: true,
			SpecTemplate: `---
asdp_version: "{{.ASDPVersion}}"
last_modified: {{.LastModified}}
id: "{{.ID}}"
type: "{{.Type}}"
title: "{{.Title}}"
summary: "{{.Summary}}"
capabilities: []
dependencies: []
requirements: []
exports: []
---
# {{.Title}} Specification

## Context
{{.Context}}

## Requirements
- ...
`,
			ModelTemplate: `---
asdp_version: "{{.ASDPVersion}}"
integrity:
  src_hash: "PENDING_FIRST_SYNC"
  algorithm: "sha256"
  checked_at: {{.CheckedAt}}
symbols: []
---
# Semantic Model

Auto-generated by ASDP. Run asdp_sync to populate.
`,
		},
		Sync: SyncConfig{
			Tree: TreeSyncConfig{
				ShallowDirs:      []string{"node_modules", "vendor", "bower_components"},
				DefaultComponent: "module",
				DependencyType:   "dependency",
				HeaderTemplate:   "\n# Project Hierarchy\n\nAuto-generated by ASDP SyncTree.\n",
				FallbackDesc:     "(No specification found)",
			},
			Model: ModelSyncConfig{
				IntegrityAlgo:  "sha256",
				FirstSyncHash:  "PENDING_FIRST_SYNC",
				HeaderTemplate: "\n# Semantic Model\n\nAuto-generated by ASDP Sync.\n",
			},
		},
		Validation: ValidationConfig{
			MandatoryFiles:   []string{"codetree.md"},
			ModuleFiles:      []string{"codespec.md", "codemodel.md"},
			ForbiddenStrings: []string{"TODO"},
			RequiredSpecKeys: []string{"title:", "summary:", "## Context"},
			Freshness: FreshnessConfig{
				WatchedExtensions: []string{".go", ".ts", ".js", ".py"},
				IgnoredExtensions: []string{".md", "_test.go"},
			},
		},
	}
}
