package usecase

import (
	"bytes"
	"fmt"
	"path/filepath"
	"text/template"
	"time"

	"github.com/Josepavese/asdp/engine/domain"
)

// Templates constants
const codeSpecTemplate = `---
asdp_version: "{{.ASDPVersion}}"
id: "{{.ID}}"
type: "{{.Type}}"
title: "{{.Name}}"
summary: "TODO: Add a brief summary of this module."
capabilities: []
dependencies: []
requirements: []
exports: []
---
# {{.Name}} Specification

## Context
Describe the context and reasoning for this module here.

## Requirements
- ...
`

const codeModelTemplate = `---
asdp_version: "{{.ASDPVersion}}"
integrity:
  src_hash: "PENDING_FIRST_SYNC"
  algorithm: "sha256"
  checked_at: {{.CheckedAt}}
symbols: []
---
# Semantic Model

Auto-generated by ASDP. Run asdp_sync to populate.
`

type ScaffoldUseCase struct {
	fs domain.FileSystem
}

type ScaffoldParams struct {
	Name string
	Type string // library, service, app
	Path string // Parent directory, default "."
}

func NewScaffoldUseCase(fs domain.FileSystem) *ScaffoldUseCase {
	return &ScaffoldUseCase{fs: fs}
}

func (uc *ScaffoldUseCase) Execute(params ScaffoldParams) (string, error) {
	absPath, err := validateAndExpandPath(params.Path)
	if err != nil {
		return "", err
	}
	params.Path = absPath

	targetDir := params.Path
	moduleName := params.Name

	if params.Name == "." || params.Name == "" {
		targetDir = params.Path
		moduleName = filepath.Base(params.Path)
	} else {
		targetDir = filepath.Join(params.Path, params.Name)
	}

	// 2. Create Directory
	if err := uc.fs.MkdirAll(targetDir); err != nil {
		// Even if it exists, we try to ensure it's there.
		// If FileSystem doesn't support it, we might skip it.
	}

	// 3. Generate Content
	specContent, err := renderTemplate(codeSpecTemplate, map[string]interface{}{
		"Name":        moduleName,
		"Type":        params.Type,
		"ASDPVersion": domain.Version,
	})
	if err != nil {
		return "", err
	}

	modelContent, err := renderTemplate(codeModelTemplate, map[string]interface{}{
		"CheckedAt":   time.Now().Format(time.RFC3339),
		"ASDPVersion": domain.Version,
	})
	if err != nil {
		return "", err
	}

	// 4. Write Files (Safely)
	files := map[string]string{
		"codespec.md":  specContent,
		"codemodel.md": modelContent,
	}

	created := []string{}
	skipped := []string{}

	for filename, content := range files {
		filePath := filepath.Join(targetDir, filename)
		if _, err := uc.fs.Stat(filePath); err == nil {
			skipped = append(skipped, filename)
			continue
		}

		// Attempt write
		if err := uc.fs.WriteFile(filePath, []byte(content)); err != nil {
			return "", fmt.Errorf("failed to write %s: %w", filename, err)
		}
		created = append(created, filename)
	}

	msg := fmt.Sprintf("Scaffolded %s in %s. Created: %v, Skipped: %v", moduleName, targetDir, created, skipped)

	if len(created) > 0 {
		msg += "\n\n[ACTION REQUIRED] You MUST now edit 'codespec.md' to remove TODOs and populate the Summary/Title fields. Failure to do so will cause 'asdp_query_context' to report validation errors."
	}

	return msg, nil
}

func renderTemplate(tmplStr string, data interface{}) (string, error) {
	t, err := template.New("scaffold").Parse(tmplStr)
	if err != nil {
		return "", err
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}
